POST /members HTTP/1.1
Host: localhost:8000
Accept: */*
Content-Type: application/json

{
  "name": "test",
  "email": "wezxasqw@gmail.com",
  "level": "1"
}

###

GET /members HTTP/1.1
Host: localhost:8000
Accept: */*

###

GET /members/1 HTTP/1.1
Host: localhost:8000
Accept: */*

###

PUT /members/1 HTTP/1.1
Host: localhost:8000
Accept: */*
Content-Type: application/json

{
  "email": "wezxasqw@gmail.com",
  "level": "1",
  "name": "put new name of member"
}

###

DELETE /members/1 HTTP/1.1
Host: localhost:8000
Accept: */*

###

GET /members HTTP/1.1
Host: localhost:8000
Accept: */*
Authorization: Basic dGVzdDpwYXNzd29yZA==
